FROM registry.access.redhat.com/ubi9/python-311:1-62.1714671026
COPY src .
USER root
RUN mkdir -p ./mnt/models
RUN chmod 755 -R ./mnt/models
USER 1001
RUN pip install --no-cache-dir --verbose -r ./requirements.txt
EXPOSE 8001
ENTRYPOINT [ "sh", "./run.sh" ]
